local a = <info descr="null" textAttributesKey="LUAU_STDLIB">Enum</info>.<info descr="null" textAttributesKey="LUAU_STDLIB">Font</info>.<info descr="null" textAttributesKey="LUAU_STDLIB">BuilderSansBold</info>
-- There is a workspace class, but it's an instance and can only be get through game:GetService("Workspace")
Workspace:FindFirstChild(pluginName .. "DebugFlags")
<info descr="null" textAttributesKey="LUAU_STDLIB">game</info>:<info descr="null" textAttributesKey="LUAU_STDLIB">GetService</info>("Workspace")
<info textAttributesKey="LUAU_STDLIB">collectgarbage</info>("count")
