<info descr="null" textAttributesKey="LUAU_KEYWORD">type</info> <info descr="null" textAttributesKey="LUAU_TYPE">A</info><<info descr="null" textAttributesKey="LUAU_TYPE_PARAMETER">B</info>> = <info descr="null" textAttributesKey="LUAU_TYPE">C</info><<info descr="null" textAttributesKey="LUAU_TYPE_PARAMETER">B</info><>>

function test<<info descr="null" textAttributesKey="LUAU_TYPE_PARAMETER">T</info>>(a: <info descr="null" textAttributesKey="LUAU_TYPE_PARAMETER">T</info>, b: <info descr="null" textAttributesKey="LUAU_TYPE">number</info>): (<info descr="null" textAttributesKey="LUAU_TYPE_PARAMETER">T</info>, <info descr="null" textAttributesKey="LUAU_TYPE">number</info>)
    <info descr="null" textAttributesKey="LUAU_KEYWORD">type</info> <info descr="null" textAttributesKey="LUAU_TYPE">A</info> = <info descr="null" textAttributesKey="LUAU_TYPE_PARAMETER">T</info>

    local t: <info descr="null" textAttributesKey="LUAU_TYPE_PARAMETER">T</info> = nil
    local c: <info descr="null" textAttributesKey="LUAU_TYPE">A</info> = a
end

local t: <info descr="null" textAttributesKey="LUAU_TYPE">T</info> = nil
